base_url = "https://not-matthias.github.io"
title = "not-matthias"
build_search_index = false
generate_feeds = true
minify_html = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

[link_checker]
internal_level = "warn"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
  { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
use_cdn = false
theme = "toggle"

menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/projects", url = "/projects", weight = 2 },
  { name = "/talks", url = "/talks", weight = 3 },
]

socials = [
  { name = "twitter", url = "https://twitter.com/not_matthias", icon = "twitter" },
  { name = "github", url = "https://github.com/not-matthias/", icon = "github" },
  { name = "rss", url = "/atom.xml", icon = "rss" },
]

[extra.taxonomies]
sort_by = "name"
reverse = false

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "not-matthias"

[extra.analytics.umami]
website_id = "74344cd8-1e87-4c38-8acd-f96049b8f07e"
