base_url = "https://not-matthias.github.io"
title = "not-matthias"
build_search_index = true
generate_feed = true
minify_html = true

theme = "apollo"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
use_cdn = false
theme = "auto"

menu = [
    { name = "/posts", url= "/posts", weight= 1 },
    { name= "/projects", url= "/projects", weight= 2 },
    { name= "/talks", url= "/talks", weight= 3 },
    { name= "/about", url= "/about", weight= 4 },
]

socials = [
    { name= "twitter", url= "https://twitter.com/not_matthias", icon= "twitter" },
    { name= "github", url= "https://github.com/not-matthias/", icon = "github" },
]

[extra.analytics]
enabled = true
goatcounter_user = "not-matthias"
